# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

python:
  install:
    - method: pip
      path: .

conda:
  environment: "env-readthedocs.yml"

#build:
#  os: ubuntu-22.04
#  tools:
#    python: "3.9"
